# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Ben\Documents\_dev\OpenGL\BensOpenGLBase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Ben\Documents\_dev\OpenGL\BensOpenGLBase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Ben\Documents\_dev\OpenGL\BensOpenGLBase\CMakeFiles C:\Users\Ben\Documents\_dev\OpenGL\BensOpenGLBase\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Ben\Documents\_dev\OpenGL\BensOpenGLBase\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ImGui

# Build rule for target.
ImGui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ImGui
.PHONY : ImGui

# fast build rule for target.
ImGui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/build
.PHONY : ImGui/fast

#=============================================================================
# Target rules for targets named COMP3016-PCG

# Build rule for target.
COMP3016-PCG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 COMP3016-PCG
.PHONY : COMP3016-PCG

# fast build rule for target.
COMP3016-PCG/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/build
.PHONY : COMP3016-PCG/fast

#=============================================================================
# Target rules for targets named copy-resources

# Build rule for target.
copy-resources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 copy-resources
.PHONY : copy-resources

# fast build rule for target.
copy-resources/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\copy-resources.dir\build.make CMakeFiles/copy-resources.dir/build
.PHONY : copy-resources/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glad\CMakeFiles\glad.dir\build.make dependencies/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\CMakeFiles\uninstall.dir\build.make dependencies/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\src\CMakeFiles\update_mappings.dir\build.make dependencies/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\src\CMakeFiles\glfw.dir\build.make dependencies/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\boing.dir\build.make dependencies/glfw/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\gears.dir\build.make dependencies/glfw/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\heightmap.dir\build.make dependencies/glfw/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named offscreen

# Build rule for target.
offscreen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 offscreen
.PHONY : offscreen

# fast build rule for target.
offscreen/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\offscreen.dir\build.make dependencies/glfw/examples/CMakeFiles/offscreen.dir/build
.PHONY : offscreen/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\particles.dir\build.make dependencies/glfw/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\sharing.dir\build.make dependencies/glfw/examples/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\simple.dir\build.make dependencies/glfw/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\splitview.dir\build.make dependencies/glfw/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\examples\CMakeFiles\wave.dir\build.make dependencies/glfw/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\clipboard.dir\build.make dependencies/glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\events.dir\build.make dependencies/glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\msaa.dir\build.make dependencies/glfw/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\glfwinfo.dir\build.make dependencies/glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\iconify.dir\build.make dependencies/glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\monitors.dir\build.make dependencies/glfw/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\reopen.dir\build.make dependencies/glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\cursor.dir\build.make dependencies/glfw/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\empty.dir\build.make dependencies/glfw/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\gamma.dir\build.make dependencies/glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\icon.dir\build.make dependencies/glfw/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\inputlag.dir\build.make dependencies/glfw/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\joysticks.dir\build.make dependencies/glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\opacity.dir\build.make dependencies/glfw/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\tearing.dir\build.make dependencies/glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\threads.dir\build.make dependencies/glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\timeout.dir\build.make dependencies/glfw/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\title.dir\build.make dependencies/glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\triangle-vulkan.dir\build.make dependencies/glfw/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) $(MAKESILENT) -f dependencies\glfw\tests\CMakeFiles\windows.dir\build.make dependencies/glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

dependencies/imgui/backends/imgui_impl_glfw.obj: dependencies/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.obj

# target to build an object file
dependencies/imgui/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.cpp.obj

dependencies/imgui/backends/imgui_impl_glfw.i: dependencies/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
dependencies/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.cpp.i

dependencies/imgui/backends/imgui_impl_glfw.s: dependencies/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
dependencies/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : dependencies/imgui/backends/imgui_impl_glfw.cpp.s

dependencies/imgui/backends/imgui_impl_opengl3.obj: dependencies/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
dependencies/imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.cpp.obj

dependencies/imgui/backends/imgui_impl_opengl3.i: dependencies/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
dependencies/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.cpp.i

dependencies/imgui/backends/imgui_impl_opengl3.s: dependencies/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
dependencies/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : dependencies/imgui/backends/imgui_impl_opengl3.cpp.s

dependencies/imgui/imgui.obj: dependencies/imgui/imgui.cpp.obj
.PHONY : dependencies/imgui/imgui.obj

# target to build an object file
dependencies/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui.cpp.obj
.PHONY : dependencies/imgui/imgui.cpp.obj

dependencies/imgui/imgui.i: dependencies/imgui/imgui.cpp.i
.PHONY : dependencies/imgui/imgui.i

# target to preprocess a source file
dependencies/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui.cpp.i
.PHONY : dependencies/imgui/imgui.cpp.i

dependencies/imgui/imgui.s: dependencies/imgui/imgui.cpp.s
.PHONY : dependencies/imgui/imgui.s

# target to generate assembly for a file
dependencies/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui.cpp.s
.PHONY : dependencies/imgui/imgui.cpp.s

dependencies/imgui/imgui_demo.obj: dependencies/imgui/imgui_demo.cpp.obj
.PHONY : dependencies/imgui/imgui_demo.obj

# target to build an object file
dependencies/imgui/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_demo.cpp.obj
.PHONY : dependencies/imgui/imgui_demo.cpp.obj

dependencies/imgui/imgui_demo.i: dependencies/imgui/imgui_demo.cpp.i
.PHONY : dependencies/imgui/imgui_demo.i

# target to preprocess a source file
dependencies/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_demo.cpp.i
.PHONY : dependencies/imgui/imgui_demo.cpp.i

dependencies/imgui/imgui_demo.s: dependencies/imgui/imgui_demo.cpp.s
.PHONY : dependencies/imgui/imgui_demo.s

# target to generate assembly for a file
dependencies/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_demo.cpp.s
.PHONY : dependencies/imgui/imgui_demo.cpp.s

dependencies/imgui/imgui_draw.obj: dependencies/imgui/imgui_draw.cpp.obj
.PHONY : dependencies/imgui/imgui_draw.obj

# target to build an object file
dependencies/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_draw.cpp.obj
.PHONY : dependencies/imgui/imgui_draw.cpp.obj

dependencies/imgui/imgui_draw.i: dependencies/imgui/imgui_draw.cpp.i
.PHONY : dependencies/imgui/imgui_draw.i

# target to preprocess a source file
dependencies/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_draw.cpp.i
.PHONY : dependencies/imgui/imgui_draw.cpp.i

dependencies/imgui/imgui_draw.s: dependencies/imgui/imgui_draw.cpp.s
.PHONY : dependencies/imgui/imgui_draw.s

# target to generate assembly for a file
dependencies/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_draw.cpp.s
.PHONY : dependencies/imgui/imgui_draw.cpp.s

dependencies/imgui/imgui_tables.obj: dependencies/imgui/imgui_tables.cpp.obj
.PHONY : dependencies/imgui/imgui_tables.obj

# target to build an object file
dependencies/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_tables.cpp.obj
.PHONY : dependencies/imgui/imgui_tables.cpp.obj

dependencies/imgui/imgui_tables.i: dependencies/imgui/imgui_tables.cpp.i
.PHONY : dependencies/imgui/imgui_tables.i

# target to preprocess a source file
dependencies/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_tables.cpp.i
.PHONY : dependencies/imgui/imgui_tables.cpp.i

dependencies/imgui/imgui_tables.s: dependencies/imgui/imgui_tables.cpp.s
.PHONY : dependencies/imgui/imgui_tables.s

# target to generate assembly for a file
dependencies/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_tables.cpp.s
.PHONY : dependencies/imgui/imgui_tables.cpp.s

dependencies/imgui/imgui_widgets.obj: dependencies/imgui/imgui_widgets.cpp.obj
.PHONY : dependencies/imgui/imgui_widgets.obj

# target to build an object file
dependencies/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_widgets.cpp.obj
.PHONY : dependencies/imgui/imgui_widgets.cpp.obj

dependencies/imgui/imgui_widgets.i: dependencies/imgui/imgui_widgets.cpp.i
.PHONY : dependencies/imgui/imgui_widgets.i

# target to preprocess a source file
dependencies/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_widgets.cpp.i
.PHONY : dependencies/imgui/imgui_widgets.cpp.i

dependencies/imgui/imgui_widgets.s: dependencies/imgui/imgui_widgets.cpp.s
.PHONY : dependencies/imgui/imgui_widgets.s

# target to generate assembly for a file
dependencies/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ImGui.dir\build.make CMakeFiles/ImGui.dir/dependencies/imgui/imgui_widgets.cpp.s
.PHONY : dependencies/imgui/imgui_widgets.cpp.s

src/common/ModelLoader.obj: src/common/ModelLoader.cpp.obj
.PHONY : src/common/ModelLoader.obj

# target to build an object file
src/common/ModelLoader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ModelLoader.cpp.obj
.PHONY : src/common/ModelLoader.cpp.obj

src/common/ModelLoader.i: src/common/ModelLoader.cpp.i
.PHONY : src/common/ModelLoader.i

# target to preprocess a source file
src/common/ModelLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ModelLoader.cpp.i
.PHONY : src/common/ModelLoader.cpp.i

src/common/ModelLoader.s: src/common/ModelLoader.cpp.s
.PHONY : src/common/ModelLoader.s

# target to generate assembly for a file
src/common/ModelLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ModelLoader.cpp.s
.PHONY : src/common/ModelLoader.cpp.s

src/common/Shader.obj: src/common/Shader.cpp.obj
.PHONY : src/common/Shader.obj

# target to build an object file
src/common/Shader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/Shader.cpp.obj
.PHONY : src/common/Shader.cpp.obj

src/common/Shader.i: src/common/Shader.cpp.i
.PHONY : src/common/Shader.i

# target to preprocess a source file
src/common/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/Shader.cpp.i
.PHONY : src/common/Shader.cpp.i

src/common/Shader.s: src/common/Shader.cpp.s
.PHONY : src/common/Shader.s

# target to generate assembly for a file
src/common/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/Shader.cpp.s
.PHONY : src/common/Shader.cpp.s

src/common/ShaderLoader.obj: src/common/ShaderLoader.cpp.obj
.PHONY : src/common/ShaderLoader.obj

# target to build an object file
src/common/ShaderLoader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ShaderLoader.cpp.obj
.PHONY : src/common/ShaderLoader.cpp.obj

src/common/ShaderLoader.i: src/common/ShaderLoader.cpp.i
.PHONY : src/common/ShaderLoader.i

# target to preprocess a source file
src/common/ShaderLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ShaderLoader.cpp.i
.PHONY : src/common/ShaderLoader.cpp.i

src/common/ShaderLoader.s: src/common/ShaderLoader.cpp.s
.PHONY : src/common/ShaderLoader.s

# target to generate assembly for a file
src/common/ShaderLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/ShaderLoader.cpp.s
.PHONY : src/common/ShaderLoader.cpp.s

src/common/UserInput.obj: src/common/UserInput.cpp.obj
.PHONY : src/common/UserInput.obj

# target to build an object file
src/common/UserInput.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/UserInput.cpp.obj
.PHONY : src/common/UserInput.cpp.obj

src/common/UserInput.i: src/common/UserInput.cpp.i
.PHONY : src/common/UserInput.i

# target to preprocess a source file
src/common/UserInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/UserInput.cpp.i
.PHONY : src/common/UserInput.cpp.i

src/common/UserInput.s: src/common/UserInput.cpp.s
.PHONY : src/common/UserInput.s

# target to generate assembly for a file
src/common/UserInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/common/UserInput.cpp.s
.PHONY : src/common/UserInput.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/Mesh.obj: src/model/Mesh.cpp.obj
.PHONY : src/model/Mesh.obj

# target to build an object file
src/model/Mesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/model/Mesh.cpp.obj
.PHONY : src/model/Mesh.cpp.obj

src/model/Mesh.i: src/model/Mesh.cpp.i
.PHONY : src/model/Mesh.i

# target to preprocess a source file
src/model/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/model/Mesh.cpp.i
.PHONY : src/model/Mesh.cpp.i

src/model/Mesh.s: src/model/Mesh.cpp.s
.PHONY : src/model/Mesh.s

# target to generate assembly for a file
src/model/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\COMP3016-PCG.dir\build.make CMakeFiles/COMP3016-PCG.dir/src/model/Mesh.cpp.s
.PHONY : src/model/Mesh.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... copy-resources
	@echo ... uninstall
	@echo ... update_mappings
	@echo ... COMP3016-PCG
	@echo ... ImGui
	@echo ... boing
	@echo ... clipboard
	@echo ... cursor
	@echo ... empty
	@echo ... events
	@echo ... gamma
	@echo ... gears
	@echo ... glad
	@echo ... glfw
	@echo ... glfwinfo
	@echo ... heightmap
	@echo ... icon
	@echo ... iconify
	@echo ... inputlag
	@echo ... joysticks
	@echo ... monitors
	@echo ... msaa
	@echo ... offscreen
	@echo ... opacity
	@echo ... particles
	@echo ... reopen
	@echo ... sharing
	@echo ... simple
	@echo ... splitview
	@echo ... tearing
	@echo ... threads
	@echo ... timeout
	@echo ... title
	@echo ... triangle-vulkan
	@echo ... wave
	@echo ... windows
	@echo ... dependencies/imgui/backends/imgui_impl_glfw.obj
	@echo ... dependencies/imgui/backends/imgui_impl_glfw.i
	@echo ... dependencies/imgui/backends/imgui_impl_glfw.s
	@echo ... dependencies/imgui/backends/imgui_impl_opengl3.obj
	@echo ... dependencies/imgui/backends/imgui_impl_opengl3.i
	@echo ... dependencies/imgui/backends/imgui_impl_opengl3.s
	@echo ... dependencies/imgui/imgui.obj
	@echo ... dependencies/imgui/imgui.i
	@echo ... dependencies/imgui/imgui.s
	@echo ... dependencies/imgui/imgui_demo.obj
	@echo ... dependencies/imgui/imgui_demo.i
	@echo ... dependencies/imgui/imgui_demo.s
	@echo ... dependencies/imgui/imgui_draw.obj
	@echo ... dependencies/imgui/imgui_draw.i
	@echo ... dependencies/imgui/imgui_draw.s
	@echo ... dependencies/imgui/imgui_tables.obj
	@echo ... dependencies/imgui/imgui_tables.i
	@echo ... dependencies/imgui/imgui_tables.s
	@echo ... dependencies/imgui/imgui_widgets.obj
	@echo ... dependencies/imgui/imgui_widgets.i
	@echo ... dependencies/imgui/imgui_widgets.s
	@echo ... src/common/ModelLoader.obj
	@echo ... src/common/ModelLoader.i
	@echo ... src/common/ModelLoader.s
	@echo ... src/common/Shader.obj
	@echo ... src/common/Shader.i
	@echo ... src/common/Shader.s
	@echo ... src/common/ShaderLoader.obj
	@echo ... src/common/ShaderLoader.i
	@echo ... src/common/ShaderLoader.s
	@echo ... src/common/UserInput.obj
	@echo ... src/common/UserInput.i
	@echo ... src/common/UserInput.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/model/Mesh.obj
	@echo ... src/model/Mesh.i
	@echo ... src/model/Mesh.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

